In [151]:
import pandas as pd
import numpy as np

In [152]:
data = pd.read_csv('People Data.csv')
data

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [153]:
data.columns

Index(['Index', 'User Id', 'First Name', 'Last Name', 'Gender', 'Email',
       'Phone', 'Date of birth', 'Job Title', 'Salary'],
      dtype='object')

In [ ]:
#1. Demonstrate three different methods for creating identical 2D arrays in NumPyƒ Provide the code for each method and the final output after each method‚
# Method 1: Using numpy.zeros()
array_method1 = np.zeros((3, 4))
print("Method 1 Output:")
print(array_method1)

# Method 2: Using numpy.ones()
array_method2 = np.ones((3, 4))
print("\nMethod 2 Output:")
print(array_method2)

# Method 3: Using numpy.full()
array_method3 = np.full((3, 4), 2)
print("\nMethod 3 Output:")
print(array_method3)

Method 1 Output:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Method 2 Output:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Method 3 Output:
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
#2.Using the Numpy function, generate an array of wRR evenly spaced numbers between w and wR and Reshape that 1D array into a 2D array
import numpy as np

# Generate the evenly spaced array
evenly_spaced_array = np.linspace(1, 10, 100)

# Reshape the 1D array into a 2D array
reshaped_array = evenly_spaced_array.reshape((10, 10))

print("Evenly spaced array:")
print(evenly_spaced_array)
print("\nReshaped 2D array:")
print(reshaped_array)


Evenly spaced array:
[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.363636

In [ ]:
#Explain the following termsg
#The difference in np.array, np.asarray and np.asanyarray
'''
np.array: This function creates a new NumPy array from an iterable (like a list or tuple) or an existing array-like object. If the input is already a NumPy array, np.array will create a new copy by default.
np.asarray: This function also creates a NumPy array from an iterable or array-like object. However, if the input is already a NumPy array, np.asarray will not create a new copy; instead, it will return the input array as is.
np.asanyarray: This function is similar to np.asarray in that it also creates a NumPy array from an iterable or array-like object. However, it guarantees that a new array is returned, even if the input is already a NumPy array. If the input is not a NumPy array, it will be converted to one.
'''

#The difference between Deep copy and shallow copy
'''
Shallow copy: A shallow copy of an object creates a new object but inserts references to the original elements into the copy. In Python, you can use the copy module's copy() function or the copy() method to perform a shallow copy.

Deep copy: creates a new object and recursively copies all the elements and sub-elements of the original object. Changes made to the deep copy do not affect the original object. In Python, you can use the copy module's deepcopy() function to perform a deep copy.
'''

"\nShallow copy: A shallow copy of an object creates a new object but inserts references to the original elements into the copy. In Python, you can use the copy module's copy() function or the copy() method to perform a shallow copy.\n\nDeep copy: creates a new object and recursively copies all the elements and sub-elements of the original object. Changes made to the deep copy do not affect the original object. In Python, you can use the copy module's deepcopy() function to perform a deep copy.\n"

In [ ]:
#Generate a 3x3array with random floating-point numbers between  5 - 20. Then, round each number in array to 2 decimal places
import numpy as np

# Generate a 3x3 array with random floating-point numbers between 5 and 20
random_array = np.random.uniform(5, 20, (3, 3))

# Round each number in the array to 2 decimal places
rounded_array = np.round(random_array, decimals=2)

print("Original Array:")
print(random_array)
print("\nRounded Array:")
print(rounded_array)

Original Array:
[[16.22469201 10.19592996 10.11245997]
 [13.25165382 12.23710736  9.93317998]
 [14.95776971 18.34164538 19.58410991]]

Rounded Array:
[[16.22 10.2  10.11]
 [13.25 12.24  9.93]
 [14.96 18.34 19.58]]


In [ ]:
#Create a NumPy array with random integers between 1 and 10 of shape (5,6). After creating the array perform the following operations:
# a)Extract all even integers from array.
# b)Extract all odd integers from array

import numpy as np

# Create a NumPy array with random integers between 1 and 10 of shape (5, 6)
random_array = np.random.randint(1, 11, size=(5, 6))

print("Original Array:")
print(random_array)

# Extract all even integers from the array
even_numbers = random_array[random_array % 2 == 0]

# Extract all odd integers from the array
odd_numbers = random_array[random_array % 2 != 0]

print("\nEven Integers:")
print(even_numbers)

print("\nOdd Integers:")
print(odd_numbers)


Original Array:
[[ 4  7  6  7  4  7]
 [ 8  6  8  2  3  1]
 [ 2  2  4  5  2  8]
 [ 4  4  5  9  8 10]
 [ 2  6  6 10  2  2]]

Even Integers:
[ 4  6  4  8  6  8  2  2  2  4  2  8  4  4  8 10  2  6  6 10  2  2]

Odd Integers:
[7 7 7 3 1 5 5 9]


In [ ]:
#Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10 Perform the following operations:
#a) Find the indices of the maximum values along each depth level (third axis).
#b) Perform elementwise multiplication of between both array
import numpy as np

# Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10
array1 = np.random.randint(1, 11, size=(3, 3, 3))
array2 = np.random.randint(1, 11, size=(3, 3, 3))
print(array1)
print(array2)

# Find the indices of the maximum values along each depth level (third axis
# a) Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array1, axis=2)
print("Indices of maximum values along third axis for array1:")
print(max_indices)

# b) Perform elementwise multiplication between both arrays
elementwise_multiplication = array1 * array2
print("\nElementwise multiplication of array1 and array2:")
print(elementwise_multiplication)


[[[2 5 5]
  [1 7 6]
  [5 4 8]]

 [[8 9 2]
  [4 9 6]
  [4 6 8]]

 [[8 6 8]
  [9 5 9]
  [5 7 9]]]
[[[ 3  3  3]
  [ 6  1  4]
  [ 8  1  9]]

 [[ 2  6  8]
  [10  6  6]
  [ 7  7  8]]

 [[ 9  3  7]
  [ 6  6  3]
  [ 7  8  6]]]
Indices of maximum values along third axis for array1:
[[1 1 2]
 [1 1 2]
 [0 0 2]]

Elementwise multiplication of array1 and array2:
[[[ 6 15 15]
  [ 6  7 24]
  [40  4 72]]

 [[16 54 16]
  [40 54 36]
  [28 42 64]]

 [[72 18 56]
  [54 30 27]
  [35 56 54]]]


In [ ]:
#Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data typeƒ Also display the taPle attriPutes and data types of each column‚
# Clean and transform the 'Phone' column
import re
# Convert the 'Phone' column to string
data['Phone'] = data['Phone'].astype(str)
# Clean and transform the 'Phone' column
data['Phone'] = [re.sub(r'\D', '', phone) for phone in data['Phone']]
# Print the transformed 'Phone' column
data['Phone']

0            8571398239
1                      
2            5997820605
3                      
4        39041716353010
             ...       
995          0217752933
996    0011497107799721
997    1750774412833265
998          9152922254
999     079752542467259
Name: Phone, Length: 1000, dtype: object

In [ ]:
data

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email             Phone Date of birth  \
0              pwarner@example.org        8571398239    27-01-2014   
1    fergusonkatherine@example.net                      26-07-1931   
2              fhoward@example.org        5997820605    25-11-2013   
3            zjohnston@example.com                      17-11-2012   
4                 elin@example.net    39041716353010    15-04-1923   
..                             ...               ...           ...   
995         lyonsdaisy@example.net        0217752933    05-01-1959   
996        dariusbryan@example.com  0011497107799721    06-10-2001   
997         georgechan@example.org  1750774412833265    13-05-1918   
998            wanda04@example.net        9152922254    31-08-1971   
999        deannablack@example.org   079752542467259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [154]:
#Perform the following tasks using people dataset:
#a) Read the 'data.csv' file using pandas, skipping the first 50 rows.
#b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.
#c) Display the first 10 rows of the filtered dataset.
#d) Extract the ‘Salary’' column as a Series and display its last 5 values
import pandas as pd
# a) Read the 'data.csv' file using pandas, skipping the first 50 rows.
data1= pd.read_csv('People Data.csv', skiprows=50)
data1

50  afF3018e9cdd1dA     George    Mercer  Female  \
0      51  CccE5DAb6E288e5         Jo    Zavala    Male   
1      52  DfBDc3621D4bcec     Joshua     Carey  Female   
2      53  f55b0A249f5E44D     Rickey     Hobbs  Female   
3      54  Ed71DcfaBFd0beE      Robyn    Reilly    Male   
4      55  FDaFD0c3f5387EC  Christina    Conrad    Male   
..    ...              ...        ...       ...     ...   
945   996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
946   997  ECddaFEDdEc4FAB      Donna     Barry  Female   
947   998  2adde51d8B8979E      Cathy  Mckinney  Female   
948   999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
949  1000  8b756f6231DDC6e        Lee      Tran  Female   

    douglascontreras@example.net    +1-326-669-0118x4341  11-09-1941  \
0           pamela64@example.net  001-859-448-9935x54536  23-11-1992   
1      dianashepherd@example.net    001-274-739-8470x814  07-01-1915   
2      ingramtiffany@example.org        241.179.9509x498  01-07-1910   
3     carriecrawford@example.org       207.797.8345x6177  27-07-1982   
4     fuentesclaudia@example.net    001-599-042-7428x143  06-01-1998   
..                           ...                     ...         ...   
945       lyonsdaisy@example.net            021.775.2933  05-01-1959   
946      dariusbryan@example.com    001-149-710-7799x721  06-10-2001   
947       georgechan@example.org   +1-750-774-4128x33265  13-05-1918   
948          wanda04@example.net           (915)292-2254  31-08-1971   
949      deannablack@example.org      079.752.5424x67259  24-01-1947   

             Human resources officer   70000  
0                       Nurse, adult   80000  
1                Seismic interpreter   70000  
2                          Barrister   60000  
3               Engineer, structural  100000  
4                    Producer, radio   50000  
..                               ...     ...  
945                Personnel officer   90000  
946          Education administrator   50000  
947  Commercial/residential surveyor   60000  
948                 Ambulance person  100000  
949       Nurse, learning disability   90000  

[950 rows x 10 columns]

In [155]:
data

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [156]:
# b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.
# b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.
data2 = pd.read_csv('People Data.csv')
selected_columns = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']
data2 = data2[selected_columns]
data2

Last Name  Gender                          Email                  Phone  \
0     Mahoney    Male            pwarner@example.org           857.139.8239   
1      Rivers  Female  fergusonkatherine@example.net                    NaN   
2      Lowery  Female            fhoward@example.org          (599)782-0605   
3      Hooper    Male          zjohnston@example.com                    NaN   
4        Rice  Female               elin@example.net     (390)417-1635x3010   
..        ...     ...                            ...                    ...   
995    Bryant  Female         lyonsdaisy@example.net           021.775.2933   
996     Barry  Female        dariusbryan@example.com   001-149-710-7799x721   
997  Mckinney  Female         georgechan@example.org  +1-750-774-4128x33265   
998    Phelps    Male            wanda04@example.net          (915)292-2254   
999      Tran  Female        deannablack@example.org     079.752.5424x67259   

     Salary  
0     90000  
1     80000  
2     50000  
3     65000  
4    100000  
..      ...  
995   90000  
996   50000  
997   60000  
998  100000  
999   90000  

[1000 rows x 5 columns]

In [158]:
# c) Display the first 10 rows of the filtered dataset.
data3= pd.read_csv('People Data.csv')
print(data3.head(10))

   Index          User Id First Name Last Name  Gender  \
0      1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1      2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2      3  810Ce0F276Badec     Sheryl    Lowery  Female   
3      4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4      5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
5      6  aF75e6dDEBC5b66     Sherry  Caldwell    Male   
6      7  efeb05c7Cc94EA3     Ernest   Hoffman    Male   
7      8  fb1BF3FED57E9d7      Doris  Andersen    Male   
8      9  421fAB9a3b98F30     Cheryl      Mays    Male   
9     10  4A42Fe10dB717CB      Harry  Mitchell    Male   

                           Email               Phone Date of birth  \
0            pwarner@example.org        857.139.8239    27-01-2014   
1  fergusonkatherine@example.net                 NaN    26-07-1931   
2            fhoward@example.org       (599)782-0605    25-11-2013   
3          zjohnston@example.com                 NaN    17-11-2012   
4          

In [159]:
#Extract the ‘Salary’' column as a Series and display its last 5 values
data4 = pd.read_csv('People Data.csv')
salary_series = data4['Salary']

# Display the last 5 values of the 'Salary' column
print("Last 5 values of the 'Salary' column:")
print(salary_series.tail())

Last 5 values of the 'Salary' column:
995     90000
996     50000
997     60000
998    100000
999     90000
Name: Salary, dtype: int64


In [161]:
#Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and ‘Salary’ should be less than 85000
data_filtered = data[(data['Last Name'] == 'Duke') & (data['Gender'] == 'Female') & (data['Salary'] < 85000)]
print(data_filtered)

     Index          User Id First Name Last Name  Gender  \
45      46  99A502C175C4EBd     Olivia      Duke  Female   
210    211  DF17975CC0a0373    Katrina      Duke  Female   
457    458  dcE1B7DE83c1076      Traci      Duke  Female   
729    730  c9b482D7aa3e682     Lonnie      Duke  Female   

                        Email                   Phone Date of birth  \
45        diana26@example.net  001-366-475-8607x04350    13-10-1934   
210       robin78@example.com            740.434.0212    21-09-1935   
457  perryhoffman@example.org     +1-903-596-0995x489    11-02-1997   
729   kevinkramer@example.net            982.692.6257    12-05-2015   

           Job Title  Salary  
45           Dentist   60000  
210  Producer, radio   50000  
457        Herbalist   50000  
729     Nurse, adult   70000  


In [162]:
#Create a 7x5. Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?
import pandas as pd
import numpy as np

# Generate 35 random integers between 1 and 6
random_integers = np.random.randint(1, 7, 35)

# Create a series from the random integers
series = pd.Series(random_integers)

# Reshape the series into a 7x5 DataFrame
data = pd.DataFrame(series.values.reshape(7, 5))

# Display the DataFrame
print("7x5 DataFrame:")
print(data)


7x5 DataFrame:
   0  1  2  3  4
0  6  5  1  5  1
1  1  2  4  1  2
2  4  1  2  2  3
3  2  2  4  1  2
4  2  6  6  3  4
5  2  3  5  1  6
6  6  6  2  1  3


In [165]:
#Create two different Series, each of length 50, with the following criteria:
#a) The first Series should contain random numbers ranging from 10 to 50.
#b) The second Series should contain random numbers ranging from 100 to 1000.
#c) Create a DataFrame by 'joining these Series by column, and, change the names of the columns to 'col1', 'col2'etc

import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(0)

# a) Create the first Series containing random numbers ranging from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, 50))
series1

# b) Create the second Series containing random numbers ranging from 100 to 1000
series2 = pd.Series(np.random.randint(100, 1001, 50))
series2


# c) Create a DataFrame by joining these Series by column and change column names
data = pd.concat([series1, series2], axis=1)
data.columns = ['col1', 'col2']  # Change column names to 'col1', 'col2', etc.

# Display the DataFrame
print("DataFrame:")
print(data)



DataFrame:
    col1  col2
0     10   153
1     13   650
2     13   588
3     49   856
4     19   373
5     29   435
6     31   488
7     46   717
8     33   142
9     16   542
10    34   643
11    34   988
12    22   357
13    11   421
14    48   157
15    49   391
16    33   970
17    34   219
18    27   879
19    47   530
20    35   182
21    23   191
22    18   996
23    19   498
24    30   711
25    26   665
26    15   733
27    25   184
28    10   303
29    28   424
30    45   874
31    34   147
32    39   739
33    29   231
34    29   968
35    24   280
36    49   946
37    42   243
38    11   760
39    19   327
40    42   891
41    41   819
42    20   473
43    33   953
44    45   660
45    21   405
46    38   681
47    44   269
48    10   775
49    10   548


In [175]:
#Perform the following operations using people data set:
#a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.
#b) Delete the rows containing any missing values.
#d) Print the final output also

import pandas as pd
data = pd.read_csv('People Data.csv')

# a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset
data.drop(['Email', 'Phone', 'Date of birth'], axis=1, inplace=True)

# b) Delete the rows containing any missing values
data.replace('', np.nan, inplace=True)
data.dropna(inplace=True)
# c) Print the final output
data


Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 7 columns]